apiVersion: apps/v1
kind: Deployment
metadata:
  name: dora-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dora-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dora-metrics
    spec:
      containers:
        - name: main
          image: shiveshabhishek/dora-metrics:v3
          command: ["python"]
          args: ["/app/main.py"]
          ports:
            - containerPort: 5000
              name: http
