apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-app-viewer-binding
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-app-viewer
subjects:
  - kind: ServiceAccount
    name: argocd-app-viewer-sa
    namespace: argocd
